### ISSUE TITLE
Not existing directory

### ISSUE THREAD

**Issue by AlexShelest** [bencikdesign/dotfiles-nasa#2]
# Symlink all files
ln -s ~/dotflies-nasa/gtk-3.0 ~/.config/gtk-3.0
ln -s ~/dotflies-nasa/mako ~/.config/mako
ln -s ~/dotflies-nasa/rofi ~/.config/rofi
ln -s ~/dotflies-nasa/sway ~/.config/sway
ln -s ~/dotflies-nasa/swaylock ~/.config/swaylock
ln -s ~/dotflies-nasa/termite ~/.config/termite
ln -s ~/dotflies-nasa/waybar ~/.config/waybar
ln -s ~/dotflies-nasa/.zshrc ~/.zshrc

in install 

change to:

# Symlink all files
cp -R ~/dotfiles-nasa/gtk-3.0 ~/.config/gtk-3.0
cp -R ~/dotfiles-nasa/mako ~/.config/mako
cp -R ~/dotfiles-nasa/rofi ~/.config/rofi
cp -R ~/dotfiles-nasa/sway ~/.config/sway
cp -R ~/dotfiles-nasa/swaylock ~/.config/swaylock
cp -R ~/dotfiles-nasa/termite ~/.config/termite
cp -R ~/dotfiles-nasa/waybar ~/.config/waybar
cp -R ~/dotfiles-nasa/.zshrc ~/.zshrc

yay -S matcha-gtk-theme reshift-wlr-gamma-control swaylock-effects-git tela-icon-theme-git otf-ibm-plex
 to 
yay -S matcha-gtk-theme redshift-wlr-gamma-control swaylock-effects-git tela-icon-theme-git otf-ibm-plex

**Comment by bencikdesign** [comment]
Hey, sorry for late response but thanks a lot for mentioning this issue in install script, fixed it now.
